import 'package:flutter/material.dart';
import 'package:translator/model/country.dart';

List<Country> listOfCountry = [
  Country(
    name: 'South Africa',
    language: 'Afrikaans',
    flag: 'assets/images/flag/za.png',
    code: 'af',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Ethiopia',
    language: 'Amharic',
    flag: 'assets/images/flag/et.png',
    code: 'am',
    textDirection: TextDirection.ltr,
  ),
  Country(
      name: "Algeria",
      language: "Arabic",
      flag: "assets/images/flag/dz.png",
      code: "ar",
      textDirection: TextDirection.rtl),
  Country(
      name: "Bahrain",
      language: "Arabic",
      flag: "assets/images/flag/bh.png",
      code: "ar",
      textDirection: TextDirection.rtl),
  Country(
    name: 'Chad',
    language: 'Arabic',
    flag: 'assets/images/flag/td.png',
    code: 'ar',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Egypt',
    language: 'Arabic',
    flag: 'assets/images/flag/eg.png',
    code: 'ar',
    textDirection: TextDirection.rtl,
  ),
  Country(
    name: 'Iraq',
    language: 'Arabic',
    flag: 'assets/images/flag/iq.png',
    code: 'ar',
    textDirection: TextDirection.rtl,
  ),
  Country(
    name: 'Jordan',
    language: 'Arabic',
    flag: 'assets/images/flag/jo.png',
    code: 'ar',
    textDirection: TextDirection.rtl,
  ),
  Country(
    name: 'Kuwait',
    language: 'Arabic',
    flag: 'assets/images/flag/kw.png',
    code: 'ar',
    textDirection: TextDirection.rtl,
  ),
  Country(
    name: 'Lebanon',
    language: 'Arabic',
    flag: 'assets/images/flag/lb.png',
    code: 'ar',
    textDirection: TextDirection.rtl,
  ),
  Country(
    name: 'Libya',
    language: 'Arabic',
    flag: 'assets/images/flag/ly.png',
    code: 'ar',
    textDirection: TextDirection.rtl,
  ),
  Country(
    name: 'Morocco',
    language: 'Arabic',
    flag: 'assets/images/flag/ma.png',
    code: 'ar',
    textDirection: TextDirection.rtl,
  ),
  Country(
    name: 'Oman',
    language: 'Arabic',
    flag: 'assets/images/flag/om.png',
    code: 'ar',
    textDirection: TextDirection.rtl,
  ),
  Country(
    name: 'Palestine',
    language: 'Arabic',
    flag: 'assets/images/flag/ps.png',
    code: 'ar',
    textDirection: TextDirection.rtl,
  ),
  Country(
    name: 'Qatar',
    language: 'Arabic',
    flag: 'assets/images/flag/qa.png',
    code: 'ar',
    textDirection: TextDirection.rtl,
  ),
  Country(
    name: 'Saudi Arabia',
    language: 'Arabic',
    flag: 'assets/images/flag/sa.png',
    code: 'ar',
    textDirection: TextDirection.rtl,
  ),
  Country(
    name: 'Sudan',
    language: 'Arabic',
    flag: 'assets/images/flag/sd.png',
    code: 'ar',
    textDirection: TextDirection.rtl,
  ),
  Country(
    name: 'Syria',
    language: 'Arabic',
    flag: 'assets/images/flag/sy.png',
    code: 'ar',
    textDirection: TextDirection.rtl,
  ),
  Country(
    name: 'Tunisia',
    language: 'Arabic',
    flag: 'assets/images/flag/tn.png',
    code: 'ar',
    textDirection: TextDirection.rtl,
  ),
  Country(
    name: 'United Arab Emirates',
    language: 'Arabic',
    flag: 'assets/images/flag/ae.png',
    code: 'ar',
    textDirection: TextDirection.rtl,
  ),
  Country(
    name: 'Yemen',
    language: 'Arabic',
    flag: 'assets/images/flag/ye.png',
    code: 'ar',
    textDirection: TextDirection.rtl,
  ),
  Country(
    name: 'Spain',
    language: 'Spanish',
    flag: 'assets/images/flag/es.png',
    code: 'eu',
    textDirection: TextDirection.ltr,
  ),
  Country(
      name: "Bangladesh",
      language: "Bengali",
      flag: "assets/images/flag/bd.png",
      code: "bn",
      textDirection: TextDirection.ltr),
  Country(
    name: 'India',
    language: 'Bengali',
    flag: 'assets/images/flag/in.png',
    code: 'bn',
    textDirection: TextDirection.ltr,
  ),
  Country(
      name: "Bosnia and Herzegovina",
      language: "Bosnian",
      flag: "assets/images/flag/ba.png",
      code: "bs",
      textDirection: TextDirection.ltr),
  Country(
    name: 'Bulgaria',
    language: 'Bulgarian',
    flag: 'assets/images/flag/bg.png',
    code: 'bg',
    textDirection: TextDirection.ltr,
  ),
  Country(
      name: "Spain",
      language: "Catalan",
      flag: "assets/images/flag/es.png",
      code: "ca",
      textDirection: TextDirection.ltr),
  Country(
    name: 'Philippines',
    language: 'Filipino',
    flag: 'assets/images/flag/ph.png',
    code: 'ceb',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'China',
    language: 'Chinese (Simplified)',
    flag: 'assets/images/flag/cn.png',
    code: 'zh-cn',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Taiwan',
    language: 'Chinese (Traditional)',
    flag: 'assets/images/flag/tw.png',
    code: 'zh-tw',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'France',
    language: 'Corsican',
    flag: 'assets/images/flag/fr.png',
    code: 'co',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Croatia',
    language: 'Croatian',
    flag: 'assets/images/flag/hr.png',
    code: 'hr',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Czech Republic',
    language: 'Czech',
    flag: 'assets/images/flag/cz.png',
    code: 'cs',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Denmark',
    language: 'Danish',
    flag: 'assets/images/flag/dk.png',
    code: 'da',
    textDirection: TextDirection.ltr,
  ),
  Country(
      name: "Belgium",
      language: "Dutch",
      flag: "assets/images/flag/be.png",
      code: "nl",
      textDirection: TextDirection.ltr),
  Country(
    name: 'Netherlands',
    language: 'Dutch',
    flag: 'assets/images/flag/nl.png',
    code: 'nl',
    textDirection: TextDirection.ltr,
  ),
  Country(
      name: "Australia",
      language: "English",
      flag: "assets/images/flag/au.png",
      code: "en",
      textDirection: TextDirection.ltr),
  Country(
    name: 'Canada',
    language: 'English',
    flag: 'assets/images/flag/ca.png',
    code: 'en',
    textDirection: TextDirection.ltr,
  ),
  Country(
      name: "India",
      language: "English",
      flag: "assets/images/flag/in.png",
      code: "en",
      textDirection: TextDirection.ltr),
  Country(
    name: 'Ireland',
    language: "English",
    flag: 'assets/images/flag/ie.png',
    code: 'en',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Kenya',
    language: "English",
    flag: 'assets/images/flag/ke.png',
    code: 'en',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'New Zealand',
    language: 'English',
    flag: 'assets/images/flag/nz.png',
    code: 'en',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Philippines',
    language: 'English',
    flag: 'assets/images/flag/ph.png',
    code: 'en',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Singapore',
    language: 'English',
    flag: 'assets/images/flag/sg.png',
    code: 'en',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'United Kingdom',
    language: 'English',
    flag: 'assets/images/flag/gb.png',
    code: 'en',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'United States',
    language: 'English',
    flag: 'assets/images/flag/us.png',
    code: 'en',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Estonia',
    language: 'Estonian',
    flag: 'assets/images/flag/ee.png',
    code: 'et',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Philippines',
    language: 'Filipino (Tagalog)',
    flag: 'assets/images/flag/ph.png',
    code: 'tl',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Finland',
    language: 'Finnish, Swedish',
    flag: 'assets/images/flag/fi.png',
    code: 'fi',
    textDirection: TextDirection.ltr,
  ),
  Country(
      name: "Belgium",
      language: "French",
      flag: "assets/images/flag/be.png",
      code: "fr",
      textDirection: TextDirection.ltr),
  Country(
    name: 'Canada',
    language: 'French',
    flag: 'assets/images/flag/ca.png',
    code: 'fr',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'France',
    language: 'French',
    flag: 'assets/images/flag/fr.png',
    code: 'fr',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Switzerland',
    language: 'French',
    flag: 'assets/images/flag/ch.png',
    code: 'fr',
    textDirection: TextDirection.ltr,
  ),
  Country(
      name: "Spain",
      language: "Galician",
      flag: "assets/images/flag/es.png",
      code: "gl",
      textDirection: TextDirection.ltr),
  Country(
    name: 'Georgia',
    language: 'Georgian',
    flag: 'assets/images/flag/gr.png',
    code: 'ka',
    textDirection: TextDirection.ltr,
  ),
  Country(
      name: "Austria",
      language: "German",
      flag: "assets/images/flag/at.png",
      code: "de",
      textDirection: TextDirection.ltr),
  Country(
    name: 'Germany',
    language: 'German',
    flag: 'assets/images/flag/de.png',
    code: 'de',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Liechtenstein',
    language: 'German',
    flag: 'assets/images/flag/li.png',
    code: 'de',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Switzerland',
    language: 'German',
    flag: 'assets/images/flag/ch.png',
    code: 'de',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Greece',
    language: 'Greek',
    flag: 'assets/images/flag/gr.png',
    code: 'el',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'India',
    language: 'Gujarati',
    flag: 'assets/images/flag/in.png',
    code: 'gu',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Haiti',
    language: 'Haitian Creole',
    flag: 'assets/images/flag/ht.png',
    code: 'ht',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Israel',
    language: 'Hebrew',
    flag: 'assets/images/flag/il.png',
    code: 'he',
    textDirection: TextDirection.rtl,
  ),
  Country(
    name: 'India',
    language: 'Hindi',
    flag: 'assets/images/flag/in.png',
    code: 'hi',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Hungary',
    language: 'Hungarian',
    flag: 'assets/images/flag/hu.png',
    code: 'hu',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Iceland',
    language: 'Icelandic',
    flag: 'assets/images/flag/is.png',
    code: 'is',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Nigeria',
    language: 'Igbo',
    flag: 'assets/images/flag/ng.png',
    code: 'ig',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Indonesia',
    language: 'Indonesian',
    flag: 'assets/images/flag/id.png',
    code: 'id',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Ireland',
    language: 'Irish',
    flag: 'assets/images/flag/ie.png',
    code: 'ga',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Italy',
    language: 'Italian',
    flag: 'assets/images/flag/it.png',
    code: 'it',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Switzerland',
    language: 'Italian',
    flag: 'assets/images/flag/ch.png',
    code: 'it',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Japan',
    language: 'Japanese',
    flag: 'assets/images/flag/jp.png',
    code: 'ja',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Indonesia',
    language: 'Javanese',
    flag: 'assets/images/flag/id.png',
    code: 'jw',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'India',
    language: 'Kannada',
    flag: 'assets/images/flag/in.png',
    code: 'kn',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Kazakhstan',
    language: 'Kazakh',
    flag: 'assets/images/flag/kz.png',
    code: 'kk',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Cambodia',
    language: 'Khmer',
    flag: 'assets/images/flag/kh.png',
    code: 'km',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'South Korea',
    language: 'Korean',
    flag: 'assets/images/flag/kr.png',
    code: 'ko',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Kurdistan',
    language: 'Kurdish (Kurmanji)',
    flag: 'assets/images/flag/OIP.png',
    code: 'ku',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Kyrgyzstan',
    language: 'Kyrgyz',
    flag: 'assets/images/flag/kg.png',
    code: 'ky',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Laos',
    language: 'Lao',
    flag: 'assets/images/flag/la.png',
    code: 'lo',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Latvia',
    language: 'Latvian',
    flag: 'assets/images/flag/lv.png',
    code: 'lv',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Lithuania',
    language: 'Lithuanian',
    flag: 'assets/images/flag/lt.png',
    code: 'lt',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Luxembourg',
    language: 'Luxembourgish',
    flag: 'assets/images/flag/lu.png',
    code: 'lb',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'North Macedonia',
    language: 'Macedonian',
    flag: 'assets/images/flag/mk.png',
    code: 'mk',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Madagascar',
    language: 'Malagasy',
    flag: 'assets/images/flag/mg.png',
    code: 'mg',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Malaysia',
    language: 'Malay',
    flag: 'assets/images/flag/my.png',
    code: 'ms',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'India',
    language: 'Malayalam',
    flag: 'assets/images/flag/in.png',
    code: 'ml',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Malta',
    language: 'Maltese',
    flag: 'assets/images/flag/mt.png',
    code: 'mt',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'New Zealand',
    language: 'Maori',
    flag: 'assets/images/flag/nz.png',
    code: 'mi',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'India',
    language: 'Marathi',
    flag: 'assets/images/flag/in.png',
    code: 'mr',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Mongolia',
    language: 'Mongolian',
    flag: 'assets/images/flag/mn.png',
    code: 'mn',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Nepal',
    language: 'Nepali',
    flag: 'assets/images/flag/np.png',
    code: 'ne',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Norway',
    language: 'Norwegian (Bokmål)',
    flag: 'assets/images/flag/no.png',
    code: 'nb',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Norway',
    language: 'Norwegian (Nynorsk)',
    flag: 'assets/images/flag/no.png',
    code: 'nn',
    textDirection: TextDirection.ltr,
  ),
  Country(
      name: "Afghanistan",
      language: "Pashto",
      flag: "assets/images/flag/af.png",
      code: "ps",
      textDirection: TextDirection.rtl),
  Country(
    name: 'Pakistan',
    language: 'Pashto',
    flag: 'assets/images/flag/pk.png',
    code: 'ps',
    textDirection: TextDirection.rtl,
  ),
  Country(
    name: 'Iran',
    language: 'Persian',
    flag: 'assets/images/flag/ir.png',
    code: 'fa',
    textDirection: TextDirection.rtl,
  ),
  Country(
    name: 'Poland',
    language: 'Polish',
    flag: 'assets/images/flag/pl.png',
    code: 'pl',
    textDirection: TextDirection.ltr,
  ),
  Country(
      name: "Brazil",
      language: "Portuguese",
      flag: "assets/images/flag/br.png",
      code: "pt",
      textDirection: TextDirection.ltr),
  Country(
    name: 'Portugal',
    language: 'Portuguese',
    flag: 'assets/images/flag/pt.png',
    code: 'pt',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'India',
    language: 'Punjabi',
    flag: 'assets/images/flag/in.png',
    code: 'pa',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Pakistan',
    language: 'Punjabi',
    flag: 'assets/images/flag/pk.png',
    code: 'pa',
    textDirection: TextDirection.rtl,
  ),
  Country(
    name: 'Romania',
    language: 'Romanian',
    flag: 'assets/images/flag/ro.png',
    code: 'ro',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Russia',
    language: 'Russian',
    flag: 'assets/images/flag/ru.png',
    code: 'ru',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Samoa',
    language: 'Samoan',
    flag: 'assets/images/flag/ws.png',
    code: 'sm',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Serbia',
    language: 'Serbian',
    flag: 'assets/images/flag/rs.png',
    code: 'sr',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'South Africa',
    language: 'Sesotho',
    flag: 'assets/images/flag/za.png',
    code: 'st',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Zimbabwe',
    language: 'Shona',
    flag: 'assets/images/flag/zw.png',
    code: 'sn',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Pakistan',
    language: 'Sindhi',
    flag: 'assets/images/flag/pk.png',
    code: 'sd',
    textDirection: TextDirection.rtl,
  ),
  Country(
    name: 'Sri Lanka',
    language: 'Sinhala',
    flag: 'assets/images/flag/lk.png',
    code: 'si',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Slovakia',
    language: 'Slovak',
    flag: 'assets/images/flag/sk.png',
    code: 'sk',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Somalia',
    language: 'Somali',
    flag: 'assets/images/flag/so.png',
    code: 'so',
    textDirection: TextDirection.ltr,
  ),
  Country(
      name: "Spain",
      language: "Spanish",
      flag: "assets/images/flag/es.png",
      code: "es",
      textDirection: TextDirection.ltr),
  Country(
    name: 'Indonesia',
    language: 'Sundanese',
    flag: 'assets/images/flag/id.png',
    code: 'su',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Kenya',
    language: 'Swahili',
    flag: 'assets/images/flag/ke.png',
    code: 'sw',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Tanzania',
    language: 'Swahili',
    flag: 'assets/images/flag/tz.png',
    code: 'sw',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Sweden',
    language: 'Swedish',
    flag: 'assets/images/flag/se.png',
    code: 'sv',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Tajikistan',
    language: 'Tajik',
    flag: 'assets/images/flag/tj.png',
    code: 'tg',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'India',
    language: 'Tamil',
    flag: 'assets/images/flag/in.png',
    code: 'ta',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Sri Lanka',
    language: 'Tamil',
    flag: 'assets/images/flag/lk.png',
    code: 'ta',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'India',
    language: 'Telugu',
    flag: 'assets/images/flag/in.png',
    code: 'te',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Thailand',
    language: 'Thai',
    flag: 'assets/images/flag/th.png',
    code: 'th',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Turkey',
    language: 'Turkish',
    flag: 'assets/images/flag/tr.png',
    code: 'tr',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Ukraine',
    language: 'Ukrainian',
    flag: 'assets/images/flag/ua.png',
    code: 'uk',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'India',
    language: 'Urdu',
    flag: 'assets/images/flag/in.png',
    code: 'ur',
    textDirection: TextDirection.rtl,
  ),
  Country(
    name: 'Pakistan',
    language: 'Urdu',
    flag: 'assets/images/flag/pk.png',
    code: 'ur',
    textDirection: TextDirection.rtl,
  ),
  Country(
    name: 'Uzbekistan',
    language: 'Uzbek',
    flag: 'assets/images/flag/uz.png',
    code: 'uz',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Vietnam',
    language: 'Vietnamese',
    flag: 'assets/images/flag/vn.png',
    code: 'vi',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Netherlands',
    language: 'Western Frisian',
    flag: 'assets/images/flag/nl.png',
    code: 'fy',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'South Africa',
    language: 'Xhosa',
    flag: 'assets/images/flag/za.png',
    code: 'xh',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'United States',
    language: 'Yiddish',
    flag: 'assets/images/flag/us.png',
    code: 'yi',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'Israel',
    language: 'Yiddish',
    flag: 'assets/images/flag/il.png',
    code: 'yi',
    textDirection: TextDirection.rtl,
  ),
  Country(
    name: 'Nigeria',
    language: 'Yoruba',
    flag: 'assets/images/flag/ng.png',
    code: 'yo',
    textDirection: TextDirection.ltr,
  ),
  Country(
    name: 'South Africa',
    language: 'Zulu',
    flag: 'assets/images/flag/za.png',
    code: 'zu',
    textDirection: TextDirection.ltr,
  ),
];
